language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - cython termformat.pyx
  - python setup.py build_ext --inplace
script:
  - nosetests
